{% set name = "cppcheck" %}
{% set version = "1.89" %}
{% set sha256 = "37452d378825c7bd78116b4d7073df795fa732207d371ad5348287f811755783" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/danmar/cppcheck/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - force-char-cppcheck-1.87.patch

build:
  number: 0
  skip: True   # [win]
  script:
    - mkdir build && cd build
    - >-
      cmake ..
      -DCMAKE_INSTALL_PREFIX=$PREFIX
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_OSX_SYSROOT=${CONDA_BUILD_SYSROOT}  # [osx]
    - VERBOSE=1 make install -j ${CPU_COUNT}

requirements:
  build:
  - {{ compiler('c') }}
  - {{ compiler('cxx') }}
  host:
  - make
  - cmake
  - pcre
  run:
  - pcre

test:
  commands:
    - cppcheck --version
    - echo ';' > test.h; cppcheck --check-config test.h

about:
  description:
    Cppcheck is a static analysis tool for C/C++ code. Unlike C/C++ compilers
    and many other analysis tools it does not detect syntax errors in the code.
    Cppcheck primarily detects the types of bugs that the compilers normally do
    not detect. The goal is to detect only real errors in the code (i.e. have
    zero false positives).
  home: 'http://cppcheck.sourceforge.net/'
  dev_url: 'https://github.com/danmar/cppcheck'
  license: 'GPLv3'
  license_family: 'GPL'
  license_file: COPYING
  summary: 'A static analysis tool for C/C++ code.'

extra:
  recipe-maintainers:
    - tovrstra
