{% set name = "cppcheck" %}
{% set version = "1.83" %}
{% set sha256 = "7d3656762beee8087e234a796c900c84b004ac241301106b6a2c01ef2beff095" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/danmar/cppcheck/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True   # [win]

requirements:
  build:
  - cmake
  - toolchain

test:
  commands:
    - cppcheck --version

about:
  description:
    Cppcheck is a static analysis tool for C/C++ code. Unlike C/C++ compilers
    and many other analysis tools it does not detect syntax errors in the code.
    Cppcheck primarily detects the types of bugs that the compilers normally do
    not detect. The goal is to detect only real errors in the code (i.e. have
    zero false positives).
  home: 'http://cppcheck.sourceforge.net/'
  dev_url: 'https://github.com/danmar/cppcheck'
  license: 'GPLv3'
  license_family: 'GPL'
  license_file: COPYING
  summary: 'A static analysis tool for C/C++ code.'

extra:
  recipe-maintainers:
    - tovrstra
