{% set name = "cppcheck" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/danmar/cppcheck/archive/{{ version }}.tar.gz
  sha256: 98bcc40ac8062635b492fb096d7815376a176ae26749d6c708083f4637f7c0bb

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
    - pygments
  host:
    - python
    - pip
    - setuptools >=45
    - setuptools-scm >=3.4
    - pcre
    - tinyxml2
  run:
    - pcre
    - python
    - pygments

test:
  commands:
    - cppcheck --version
    - test "$(cppcheck --version)" == "Cppcheck $PKG_VERSION"  # [unix]
    - echo ';' > test.h; cppcheck --check-config test.h

about:
  description: Cppcheck is a static analysis tool for C/C++ code. Unlike C/C++ compilers and many other analysis tools it does not detect syntax errors in the code. Cppcheck primarily detects the types of bugs that the compilers normally do not detect. The goal is to detect only real errors in the code (i.e. have zero false
    positives).
  home: http://cppcheck.sourceforge.net/
  dev_url: https://github.com/danmar/cppcheck
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A static analysis tool for C/C++ code.

extra:
  recipe-maintainers:
    - timsnyder
    - tovrstra
    - seanyen
    - wolfv
