{% set name = "cppcheck" %}
{% set version = "2.10.1" %}
{% set sha256 = "0a1aa45d00132ecee0c9af467e085efbda448094a89d90137249b080863466d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/danmar/cppcheck/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-binary-relocation-issue-1.90.patch
    - 0001-adjust-patchversion-for-2.10.1.patch

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [osx or unix]
    - cmake
    - pygments
  host:
    - python
    - setuptools
    - pcre
  run:
    - pcre
    - python
    - pygments

test:
  commands:
    - cppcheck --version
    - test "$(cppcheck --version)" == "Cppcheck $PKG_VERSION"  # [unix]
    - echo ';' > test.h; cppcheck --check-config test.h

about:
  description: Cppcheck is a static analysis tool for C/C++ code. Unlike C/C++ compilers and many other analysis tools it does not detect syntax errors in the code. Cppcheck primarily detects the types of bugs that the compilers normally do not detect. The goal is to detect only real errors in the code (i.e. have zero false
    positives).
  home: http://cppcheck.sourceforge.net/
  dev_url: https://github.com/danmar/cppcheck
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A static analysis tool for C/C++ code.

extra:
  recipe-maintainers:
    - timsnyder
    - tovrstra
    - seanyen
