appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WS9IYU5615rCM3REiyA4mZopiEZLo4NMvpwS8yYulylGIO19EuhL5ssY1tsGalVIU7gubnMc/cyFgBdt0GxAUb6nLOOBKgyqwZsZcPbCQd2fBs6X1F2+pN8Svv3hm74VjBo1KV0k1P1gnW9FtZTds4ph2MDb2RUahTRciZL5l1DrrK/9c7kj40hseRd0AxqZnd+ROV6fsH2tkMddbyzzUJBS2224ZstJCleRJSnp0j3L6mXU+lL9/WbitlnelKkf2gMzCLZ3ojvT32XuMK3vIs8SlEO3pLWukaAeethijqe2lpxZKms59Ysk3Xr2B38p29FykHkrhSJxnBGtLpXGV2Ysw+Y/sz/cIoX0hKh61zk4zFGgc0xCiOxaTwNThacFLsZ1Q95+MVGV065QSkH2gtwyycpHQetGBZoW5DxK4cR0K60JZQ25HIJptRAUltIIxw4H7/iZ3wERbRNB9ZO3sCcu2TUaLLjz5Q5g1rH5YY01aDXb8B1ULh/WDRc/1ynqqvhHetSXnZev/wmDxZVlbMQP62FOwhKhQ4GeScMs+P0LZEnMc7yBIFGgQHDLHVgFljgq487dBza+h0jPPWKn0EbvbPIC/hx+ahKdWZF6eassHhNeYWrqgIC+tGFMe83Zhpxn8N8Xf7pGKeYFR82F89Cd89CKCU24eiHiOs2D0Bs=}
