build_platform:
  linux_aarch64: linux_64
# Punt on getting osx_arm64 to work for now. it will require
# modifying recipe and cmake files to build dmake for build platform first
# and then using it to cross-compile see #69
#  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: azure
test_on_native_only: true
conda_build:
  pkg_format: '2'
